server:
    port: 2000
spring:
    application:
        name: gateway
    config:
        import: optional:configserver:http://localhost:8081
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database: mysql
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: microestudiante
#            uri: lb://microestudiante
#            predicates:
#              - Path=/api/estudiantes/**
#          - id: microcarrera
#            uri: lb://microcarrera
#            predicates:
#              - Path=/api/carreras/**
#          - id: microinscripcion
#            uri: lb://microinscripcion
#            predicates:
#              - Path=/api/inscripciones/**
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
