server:
    port: 2001
spring:
    application:
        name: gateway
    config:
        import: optional:configserver:http://localhost:8081
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database: mysql
