server:
    port: 2000
spring:
    application:
        name: gateway
    config:
        import: optional:configserver:http://localhost:8081
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database: mysql
    cloud:
      gateway:
        mvc:
          routes:
            # Ruta al microservicio-gestor
          - id: microservicio-gestor
            uri: http://localhost:8082
            predicates:
              - Path=/api/microservicioGestor/**

          # Ruta al microservicio-monopatin
          - id: microservicio-monopatin
            uri: http://localhost:8083
            predicates:
              - Path=/api/microservicioMonopatin/**

          # Ruta al microservicio-parada
          - id: microservicio-parada
            uri: http://localhost:8084
            predicates:
              - Path=/api/microservicioParada/**

          # Ruta al microservicio-usuario
          - id: microservicio-usuario
            uri: http://localhost:8085
            predicates:
              - Path=/api/microservicioUsuario/**

          # Ruta al microservicio-viaje
          - id: microservicio-viaje
            uri: http://localhost:8086
            predicates:
              - Path=/api/microservicioViaje/**
    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
