server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: microservicio-parada
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/paradas?authSource=admin
      username: root
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
