server:
    port: ${PORT:${SERVER_PORT:0}}
spring:
    application:
        name: microservicio-monopatin
    config:
        import: optional:configserver:http://localhost:8081
    data:
        mongodb:
            uri: mongodb://localhost:27017/paradas
